"use client";

export interface TranslationContent {
  [key: string]: string | string[] | TranslationContent;
}

export interface Translations {
  [key: string]: TranslationContent;
}

export const TRANSLATIONS: Translations = {
  ge: {
    home: "მთავარი",
    homeContent: 'ეს არის "მთავარი" გვერდი.', // ქართული აღწერა
    about: "ჩვენს შესახებ",
    aboutContent: 'ეს არის "ჩვენს შესახებ" გვერდი.', // ქართული აღწერა
    contact: "კონტაქტი",
    contactContent: "დაგვიკავშირდით აქ.", // ქართული აღწერა
    auth: {
      login: "შესვლა",
      register: "რეგისტრაცია",
      email: "ელ-ფოსტა",
      password: "პაროლი",
      confirmPassword: "გაიმეორეთ პაროლი",
      rememberMe: "დამიმახსოვრე",
      forgotPassword: "დაგავიწყდათ პაროლი?",
      fullName: "სრული სახელი",
      loginButton: "შესვლა",
      registerButton: "რეგისტრაცია",
      alreadyHaveAccount: "უკვე გაქვთ ანგარიში?",
      dontHaveAccount: "არ გაქვთ ანგარიში?",
      createAccount: "შექმენით ანგარიში",
      loginWelcome: "შედით თქვენი ანგარიშით",
      loginSubtitle: "კეთილი იყოს თქვენი დაბრუნება!",
      registerWelcome: "მოგესალებით FishHunt-ის სამყაროში!",
      registerSubtitle: "გთხოვთ, შეავსოთ რეგისტრაციის ფორმა",
      requiredField: "სავალდებულო ველი",
      invalidEmail: "არასწორი ელ-ფოსტა",
      passwordTooShort: "პაროლი უნდა შეიცავდეს მინიმუმ 6 სიმბოლოს",
      passwordsDontMatch: "პაროლები არ ემთხვევა",
      termsAgreement: "ვეთანხმები მომსახურების პირობებს",
      sellerRegistration: "გამყიდვლის რეგისტრაცია",
      personalInfo: "პირადი ინფორმაცია",
      businessInfo: "ბიზნესის ინფორმაცია",
      firstName: "სახელი",
      lastName: "გვარი",
      companyName: "კომპანიის სახელი",
      phoneNumber: "ტელეფონის ნომერი",
      uploadLogo: "ატვირთეთ ლოგო",
      idNumber: "პირადი ნომერი",
      accountNumber: "ანგარიშის ნომერი",
      sellerWelcome: "მოგესალებით FishHunt-ის სამყაროში!",
      sellerSubtitle: "შექმენით თქვენი პორტფოლიო და დაიწყეთ გაყიდვები!",
      enterName: "შეიყვანეთ სახელი",
      enterEmail: "შეიყვანეთ ელ-ფოსტა",
      enterYourEmail: "შეიყვანეთ თქვენი ელ-ფოსტა",
      enterCode: "შეიყვანეთ კოდი",
      enterFirstName: "შეიყვანეთ სახელი",
      enterLastName: "შეიყვანეთ გვარი",
      enterIdNumber: "შეიყვანეთ პირადი ნომერი",
      enterCompanyName: "შეიყვანეთ კომპანიის სახელი",
      logoPreview: "ლოგოს პრევიუ",
      changeLogo: "ლოგოს შეცვლა",
      emailRequired: "ელ-ფოსტის მითითება აუცილებელია",
      enterNewPassword: "შეიყვანეთ ახალი პაროლი",
      confirmNewPassword: "დაადასტურეთ ახალი პაროლი",
      registrationSuccessful: "რეგისტრაცია წარმატებულია",
      sellerAccountCreatedSuccessfully:
        "გამყიდვლის ანგარიში წარმატებით შეიქმნა",
      accountCreatedSuccessfully: "ანგარიში წარმატებით შეიქმნა",
      redirectingToLogin: "მიმდინარეობს გადამისამართება შესვლის გვერდზე",
      loginSuccess: "წარმატებით შეხვედით",
      loginFailed: "შესვლა ვერ მოხერხდა",
      registrationFailed: "რეგისტრაცია ვერ მოხერხდა",
      orContinueWith: "ან გააგრძელეთ",
      forgotPasswordTitle: "განაახლეთ პაროლი",
      forgotPasswordSubtitle: "გთხოვთ, შეავსოთ პაროლის აღდგენის ფორმა",
    },
    categories: {
      // Main categories
      FISHING: "თევზაობა",
      HUNTING: "ნადირობა",
    },
    forum: {
      addNewPost: "➕ ახალი პოსტის დამატება",
      loadingMore: "იტვირთება მეტი...",
      addPostSeeOthers: "დაამატე პოსტი / ნახე სხვა პოსტებიც",
      edit: "რედაქტირება",
      delete: "წაშლა",
      save: "შენახვა",
      cancel: "გაუქმება",
      reply: "პასუხი",
      like: "მოწონება",
      unlike: "მოწონების გაუქმება",
      writeReply: "დაწერეთ პასუხი...",
      writeComment: "დაწერეთ კომენტარი...",
      posting: "იგზავნება...",
      send: "გაგზავნა",
      selectTag: "აირჩიეთ თეგი",
      creating: "იქმნება...",
      create: "შექმნა",
      newPost: "ახალი პოსტის შექმნა",
      writePostContent: "დაწერეთ პოსტის შინაარსი...",
      tags: {
        hunting: "ნადირობა",
        fishing: "თევზაობა",
        other: "სხვა",
      },
    },
  },
  en: {
    home: "HOME",
    homeContent: "This is the 'Home' page.", // ინგლისური აღწერა
    about: "About",
    aboutContent: "This is the 'About' page.", // ინგლისური აღწერა
    contact: "Contact",
    contactContent: "Contact us here.", // ინგლისური აღწერა
    // Authentication & Registration
    auth: {
      login: "Login",
      register: "Register",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      fullName: "Full Name",
      loginButton: "Login",
      registerButton: "Register",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      createAccount: "Create Account",
      loginWelcome: "Sign into your account",
      loginSubtitle: "Welcome back!",
      registerWelcome: "Welcome to SoulArt's World!",
      registerSubtitle: "Please fill in the registration form",
      requiredField: "This field is required",
      invalidEmail: "Invalid email address",
      passwordTooShort: "Password must be at least 6 characters",
      passwordsDontMatch: "Passwords don't match",
      termsAgreement: "I agree to the Terms of Service",
      sellerRegistration: "Seller Registration",
      personalInfo: "Personal Information",
      businessInfo: "Business Information",
      firstName: "First Name",
      lastName: "Last Name",
      companyName: "Company Name",
      phoneNumber: "Phone Number",
      uploadLogo: "Upload Logo",
      idNumber: "ID Number/Company ID",
      accountNumber: "Account Number",
      sellerWelcome: "Welcome to SoulArt's World!",
      sellerSubtitle: "Create your portfolio and start selling!",
      enterName: "Enter your name",
      enterEmail: "Enter your email",
      enterYourEmail: "Enter your email",
      enterCode: "Enter verification code",
      enterFirstName: "Enter first name",
      enterLastName: "Enter last name",
      enterIdNumber: "Enter ID number",
      enterCompanyName: "Enter company name",
      logoPreview: "Logo Preview",
      changeLogo: "Change Logo",
      emailRequired: "Email is required",
      enterNewPassword: "Enter new password",
      confirmNewPassword: "Confirm new password",
      registrationSuccessful: "Registration Successful",
      sellerAccountCreatedSuccessfully: "Seller account created successfully",
      accountCreatedSuccessfully: "Account created successfully",
      redirectingToLogin: "Redirecting to login page",
      loginSuccess: "Login Successful",
      loginFailed: "Login Failed",
      registrationFailed: "Registration Failed",
      orContinueWith: "or continue with",
      forgotPasswordTitle: "Reset Your Password",
      forgotPasswordSubtitle: "Please fill in the password recovery form",
    },
    categories: {
      // Main categories
      FISHING: "fishing",
      HUNTING: "hunting",
    },
  },
  forum: {
    addNewPost: "➕ Add new post",
    loadingMore: "Loading more...",
    addPostSeeOthers: "Add post / See other posts",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    reply: "Reply",
    like: "Like",
    unlike: "Unlike",
    writeReply: "Write a reply...",
    writeComment: "Write a comment...",
    posting: "Posting...",
    send: "Send",
    selectTag: "Select a tag",
    creating: "Creating...",
    create: "Create",
    newPost: "Create New Post",
    writePostContent: "Write your post content...",
    tags: {
      hunting: "hunting",
      fishing: "fishing",
      other: "Other",
    },
  },
};
